baseURL: https://stevenvukcevich.com
languageCode: en-us
title: My New Hugo Site
publishDir: docs

theme: reveal-hugo
markup:
  goldmark:
    renderer:
      unsafe: true
outputFormats:
  Reveal:
    baseName: index
    mediaType: text/html
    isHTML: true
