baseURL: /
languageCode: en-us
title: stevenvukcevich.com
publishDir: docs

module:
  imports:
    - path: github.com/dzello/reveal-hugo

outputFormats:
  Reveal:
    baseName: index
    mediaType: text/html
    isHTML: true
